server:
  port: 51801
spring:
  application:
    name: Vefast-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.189.128:8848
        watch-delay: 30000  # 延长等待时间，单位毫秒
      config:
        server-addr: 192.168.189.128:8848
        file-extension: yaml
  config:
    import: nacos:Vefast-user